package pkg

type CMD string

const (
	PING_CMD CMD = "PING"

	SET_CMD CMD = "SET"
	GET_CMD CMD = "GET"
	DEL_CMD CMD = "DEL"

	RPUSH_CMD  CMD = "RPUSH"
	RLEN_CMD   CMD = "RLEN"
	RRANGE_CMD CMD = "RRANGE"
	RPOP_CMD   CMD = "RPOP"
	LPOP_CMD   CMD = "LPOP"
	LPUSH_CMD  CMD = "LPUSH"
)
